---
title: "R Notebook"
output: html_notebook
---
```{r, include=FALSE}
library(tidyverse)
library(readr)
library(ggplot2)

conf_data <- read_csv("cleaned_data/conf_dely_clean.csv")
```



```{r, echo=FALSE}
#Creating the equivalent of a pivot table to show count of each response
response_count <- conf_data %>% 
  group_by(
    condition, 
    confidence_bin
    ) %>% 
  summarise(
    filler_id_ta = sum(response == "filler id (ta)"),
     innocent_id = sum(response == "innocent id"),
    innocent_rej = sum(response == "incorrect rejection"),
    filler_id_tp = sum(response == "filler id (tp)"),
      correct_id = sum(response == "correct id"),
     correct_rej = sum(response == "correct rejection")
    ) %>% 
  mutate(
    false_id_rate = (filler_id_ta + innocent_id) / 6,
    cac = correct_id/(correct_id + false_id_rate)
  )

```

```{r, echo=FALSE}
response_count %>% 
ggplot(aes(x = confidence_bin, y = cac, colour = condition)) +
geom_line() +
geom_point(size = response_count$correct_id/10) +
scale_color_manual(values = c("#006633", "#FFCC00", "#003366")) +
scale_x_continuous(breaks = c(1.0, 2.0, 3.0), labels = c("Low", "Medium", "High")) +
  labs(
    x = "Confidence",
    y = "Proportion Correct",
    colour = "Condition"
  ) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"))
```



